name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"
      - run: ./gradlew.bat build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build/libs/baustella-light-control-fat-*.jar
          if-no-files-found: error
